# Generated by Django 3.2.8 on 2021-10-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='제목'),
        ),
    ]
