# Generated by Django 3.2.8 on 2021-10-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dsuser',
            table='dstagram_user',
        ),
    ]
